# Generated by Django 3.1.14 on 2022-06-30 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Бокс №1', max_length=20, verbose_name='Название бокса')),
                ('floor', models.IntegerField(help_text='3', verbose_name='Номер этажа')),
                ('occupiid', models.BooleanField(db_index=True, default=False, verbose_name='Занят')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_index=True, max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Отчество')),
                ('pure_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='3 кг, 3-10кг', max_length=20, verbose_name='Наименование размера')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Склад на Арбате', max_length=30, verbose_name='Название склада')),
                ('address', models.TextField(help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='Адрес склада')),
                ('number_of_floors', models.IntegerField(help_text='3', verbose_name='Количество этажей')),
                ('boxes_per_floor', models.IntegerField(help_text='3', verbose_name='Количество боксов на этаже')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(help_text='3', verbose_name='Номер этажа склада')),
                ('end_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата окончания хранения')),
                ('price', models.IntegerField(db_index=True, verbose_name='Стоимость заказа')),
                ('paid', models.BooleanField(db_index=True, default=False, verbose_name='Оплачен')),
                ('boxes', models.ManyToManyField(related_name='orders', to='selfstorage.Box', verbose_name='Боксы в заказе')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='selfstorage.customer', verbose_name='Покупатель')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='selfstorage.size', verbose_name='Объём бокса')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='selfstorage.warehouse', verbose_name='Склад')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='selfstorage.customer', verbose_name='Кем занят'),
        ),
        migrations.AddField(
            model_name='box',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='selfstorage.size', verbose_name='Объём бокса'),
        ),
        migrations.AddField(
            model_name='box',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='selfstorage.warehouse', verbose_name='Склад'),
        ),
    ]
