# Generated by Django 3.1.14 on 2022-06-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstorage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='boxes',
        ),
        migrations.AddField(
            model_name='order',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='selfstorage.box', verbose_name='Боксы в заказе'),
            preserve_default=False,
        ),
    ]
