# Generated by Django 3.1.14 on 2022-07-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstorage', '0003_input_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='selfstorage.box', verbose_name='Бокс'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(help_text='г.Москва, ул.Подольских курсантов, д.5', verbose_name='Адрес склада'),
        ),
    ]
