# Generated by Django 3.1.14 on 2022-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstorage', '0004_auto_20220701_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='e_mail',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail адрес'),
        ),
    ]
