# Generated by Django 3.1.14 on 2022-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstorage', '0005_customer_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='patronymic',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
    ]
