# Generated by Django 3.1.14 on 2022-07-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstorage', '0007_auto_20220702_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
