# Generated by Django 3.1.14 on 2022-07-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstorage', '0008_auto_20220702_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='occupiid',
            new_name='occupied',
        ),
    ]
